version: "3.7"
services:
    pub-server:
        container_name: pub-server
        build:
            context: ./pub-server
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - "./pub-server/:/usr/src/app"
        networks:
            png-main-network:
                ipv4_address: 172.25.0.80
                aliases:
                    - pub-server.local

    sub-server:
        container_name: sub-server
        build:
            context: ./sub-server
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - "./sub-server/:/usr/src/app"
        networks:
            png-main-network:
                ipv4_address: 172.25.0.90
                aliases:
                    - sub-server.local
networks:

 
  png-main-network:
    ipam:
        driver: default
        config:
          - subnet: 172.25.0.0/16
